# Nazwa całego procesu (workflow)
name: Tygodniowy monitoring KRS

# Wyzwalacze (Triggers) - czyli kiedy ten proces ma się uruchomić
on:
  # Uruchomienie według harmonogramu (cron)
  # Ta linijka oznacza "uruchom w każdą niedzielę o 23:00 czasu UTC"
  schedule:
    - cron: '0 23 * * 0'
    
  # Umożliwia również ręczne uruchomienie z poziomu zakładki "Actions" na GitHubie
  workflow_dispatch:

# Definicja zadań (Jobs) do wykonania
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run script
        # TA SEKCJA JEST KLUCZOWA!
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python main.py # Albo nazwa Twojego pliku .py
