name: Monitor KRS – zmiany kapitału

on:
  # 1) Uruchom ręcznie z poziomu GitHuba (Run workflow)
  workflow_dispatch:
  # 2) Harmonogram (cron działa w UTC!)
  schedule:
    - cron: "30 05 * * *"   # codziennie o 05:30 UTC (~06:30 zimą / ~07:30 latem w PL)

permissions:
  contents: read

concurrency:
  group: monitor-krs
  cancel-in-progress: false

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    env:
      # Sekcja ENV pobiera wartości z GitHub Secrets (ustaw je wcześniej w Settings → Secrets and variables → Actions)
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}

      # (opcjonalnie) Jeżeli chcesz nadpisać liczbę dni okna bez zmiany kodu:
      # DNI_OKNA: "30"

    steps:
      - name: Sprawdź repo
        uses: actions/checkout@v4

      - name: Skonfiguruj Pythona
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Zainstaluj zależności
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # minimalny zestaw do działania
            pip install requests
          fi

      - name: Pokaż wersje i obecne pliki
        run: |
          python --version
          pip --version
          ls -la
          echo "-----"
          echo "Zawartość plików wejściowych (jeśli istnieją):"
          if [ -f krs_do_monitorowania.txt ]; then
            echo "krs_do_monitorowania.txt:"
            cat krs_do_monitorowania.txt
          else
            echo "Brak krs_do_monitorowania.txt"
          fi
          if [ -f odbiorcy.txt ]; then
            echo "odbiorcy.txt:"
            cat odbiorcy.txt
          else
            echo "Brak odbiorcy.txt"
          fi
          
- name: Utwórz odbiorcy.txt z sekretu
  run: |
    printf "%s\n" "${{ secrets.RECIPIENTS }}" > odbiorcy.txt

  
      - name: Uruchom skrypt
        run: |
          set -euo pipefail
          python main.py
