name: Monitor KRS – zmiany kapitału

on:
  workflow_dispatch:
  schedule:
    - cron: "30 05 * * *"   # codziennie o 05:30 UTC (~06:30 zimą / ~07:30 latem w PL)

permissions:
  contents: read

concurrency:
  group: monitor-krs
  cancel-in-progress: false

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    env:
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      # (opcjonalnie) DNI_OKNA: "30"

    steps:
      - name: Sprawdź repo
        uses: actions/checkout@v4

      - name: Skonfiguruj Pythona
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Zainstaluj zależności
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Utwórz odbiorcy.txt z sekretu
        # jeśli używasz opcji B (plik). Jeśli korzystasz z ENV w kodzie, ten krok pomiń.
        run: |
          printf "%s\n" "${{ secrets.RECIPIENTS }}" > odbiorcy.txt

      - name: Pokaż wersje i obecne pliki (bez wrażliwych danych)
        run: |
          python --version
          pip --version
          ls
